const CARDback      = "#505156"  // Card Background
const CARDhigh      = "#8F939C"  // Card Background - Selected
const CARDdark      = "#28272D"  // Card Background - Unavailable
const CARDgrid      = "#27262B"  // Card Squares
const CARDgridhigh  = "#45494C"  // Card Squares - Selected
const CARDgriddark  = "#131315"  // Card Squares - Unavailable
const CARDblack     = "#161416"  // Card Points Background
const CARDblackhigh = "#282C2D"  // Card Points Background - Selected
const CARDblackdark = "#09090B"  // Card Points Background - Unavailable
const CARDwhite     = "#FCFCFC"  // Card Points Text
const CARDwhitedark = "#7F7F7F"  // Card Points Text - Unavailable
const BOARDback     = "#141021"  // Game Board Back
const BOARDgrid     = "#3A394D"  // Game Board Gridlines
const INKyellow     = "#E9FF3A"  // Ink
const INKblue       = "#5B39FF"  // 
const SPECILyellow  = "#FEC002"  // Special
const SPECILblue    = "#08E9FE"  // 
const FIREyellow    = "#FCCF03"  // Special Active - Flame
const FIREblue      = "#B2E0DD"  // 
const GLOWyellow    = "#F5F30E"  // Special Active - Glow
const GLOWblue      = "#DEDADD"  // 
const BACKDROP      = "#46359D"  // General Background
const SHADOW        = "#2C2260"  // Shadow (behind cards, behind results)
const SPLATyellow   = "#8F9A54"  // Splatter behind points
const SPLATblue     = "#331D89"  // 
const POINTSyellow  = "#E1FE64"  // Points
const POINTSblue    = "#8054FE"  //
const DARKyellow    = "#656E37"  // Shadow (behind points)
const DARKblue      = "#29196A"  //
const BUTTONblue    = "#544AE9"  // Pass/Special Button
const BUTTONgrey    = "#958F9B"  // Pass/Special Button - Unavailable
const BUTTONyellow  = "#E0EB28"  // Special Button - Active
const TURNSback     = "#8C8B8E"  // Turns Counter Background
const TURNStext     = "#C8C7CA"  // Turns Left Text
const TURNSlow      = "#F74732"  // 5 Turns or Less